# Generated by Django 3.2 on 2024-03-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aluminium', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='DESIGNATION',
            field=models.CharField(default='designation', max_length=20),
        ),
        migrations.AddField(
            model_name='register',
            name='MAIL',
            field=models.CharField(default='mail', max_length=20),
        ),
        migrations.AddField(
            model_name='register',
            name='PICTURE',
            field=models.FileField(default='picture', upload_to=''),
        ),
    ]
