# Generated by Django 3.2 on 2024-03-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aluminium', '0002_auto_20240324_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='DESIGNATION',
            field=models.CharField(default='designation', max_length=30),
        ),
        migrations.AlterField(
            model_name='register',
            name='PICTURE',
            field=models.FileField(default='PICTURE', upload_to=''),
        ),
    ]
